from __future__ import annotations

from typing import Any

from .QtCore import QPoint, QRect, QRectF

class QCursor:
    def __init__(self, shape: int | Any = ...) -> None: ...

class QMouseEvent:
    def button(self) -> int: ...
    def position(self) -> QPoint: ...

class QKeyEvent:
    def key(self) -> int: ...

class QColor:
    def __init__(self, r: int = ..., g: int = ..., b: int = ..., a: int = ...) -> None: ...

class QPaintEvent: ...

class QPainter:
    def __init__(self, device: Any | None = ...) -> None: ...
    def setRenderHint(self, hint: Any, on: bool = ...) -> None: ...
    def setPen(self, pen: Any) -> None: ...
    def fillPath(self, path: QPainterPath, color: QColor) -> None: ...

class QPainterPath:
    def __init__(self) -> None: ...
    def addRect(self, rect: QRectF | QRect) -> None: ...
    def subtracted(self, other: QPainterPath) -> QPainterPath: ...

__all__ = [
    "QColor",
    "QCursor",
    "QKeyEvent",
    "QMouseEvent",
    "QPaintEvent",
    "QPainter",
    "QPainterPath",
]
