from __future__ import annotations

from typing import Any

from .QtCore import QObject, QPoint, QRect, QSize
from .QtGui import QCursor, QKeyEvent, QMouseEvent, QPaintEvent

class QWidget(QObject):
    def __init__(self, parent: QWidget | None = ..., flags: int | None = ...) -> None: ...
    def setWindowState(self, state: int) -> None: ...
    def setAttribute(self, attribute: int, on: bool = ...) -> None: ...
    def setCursor(self, cursor: QCursor) -> None: ...
    def show(self) -> None: ...
    def raise_(self) -> None: ...
    def close(self) -> None: ...
    def rect(self) -> QRect: ...
    def update(self) -> None: ...
    def mousePressEvent(self, event: QMouseEvent) -> None: ...
    def mouseMoveEvent(self, event: QMouseEvent) -> None: ...
    def mouseReleaseEvent(self, event: QMouseEvent) -> None: ...
    def keyPressEvent(self, event: QKeyEvent) -> None: ...
    def paintEvent(self, event: QPaintEvent) -> None: ...

class QRubberBand(QWidget):
    class Shape: ...
    def __init__(self, shape: int, parent: QWidget | None = ...) -> None: ...
    def setGeometry(self, rect: QRect) -> None: ...
    def geometry(self) -> QRect: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def isHidden(self) -> bool: ...

class QApplication(QObject):
    def __init__(self, argv: list[str]) -> None: ...
    def exec(self) -> int: ...

__all__ = [
    "QApplication",
    "QRubberBand",
    "QWidget",
]
